name: flutter_helpers
description: Helpers for Flutter's development. See also `dart_helpers`.
homepage: https://github.com/signmotion/flutter_helpers
publish_to: none

version: 0.1.0+100

environment:
  flutter: '>=2.10.2 <3.0.0'
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dart_helpers:
    path: ../dart_helpers

  package_info_plus: ^1.3.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

  json_annotation: ^4.5.0
