name: flutter_helpers
description: Helpers for Flutter's development. See also `dart_helpers`.
homepage: https://github.com/signmotion/flutter_helpers
publish_to: none

version: 0.1.0+100

environment:
  flutter: ">=3.10.6 <4.0.0"
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dart_helpers:
    path: ../dart_helpers

  package_info_plus: ^4.0.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

  json_annotation: ^4.5.0
