name: flutter_helpers
description: Helpers for Flutter's development. See also `dart_helpers`.
homepage: https://github.com/signmotion/flutter_helpers
publish_to: none

# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.1.0

environment:
  flutter: ">=3.16.5 <4.0.0"
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dart_helpers:
    path: ../dart_helpers

  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_lints: ^3.0.1

  flutter_test:
    sdk: flutter

  json_annotation: ^4.5.0
